name: CI Pipeline

on:
  push:
    branches:
      - master  # Vérifiez l'indentation et la branche
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Correction: 'users' à 'uses'

    - name: Install Node.js
      uses: actions/setup-node@v3  # Correction: 'users' à 'uses'
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install  # Correction: 'nmp' à 'npm'

    - name: ESLint (JS/TS) Action
      uses: iCrawl/action-eslint@v1  # Correction: 'users' à 'uses'

    - name: Run Tests
      run: npm test

      