name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install Dependencies
      run: npm install

    - name: ESLint (JS/TS) Action
      uses: iCrawl/action-eslint@v1
      with:
        custom-glob: src  # Vous pouvez définir le répertoire à analyser (si nécessaire)

    - name: Run Tests
      run: npm test

