name : CI PipLine

  on:
    push:
      branches:
      -master
    pull_request:
      branches:
        - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - users: action/checkout@v4
    
    - name : ESLint (JS/TS) Action
      users: iCrawl/action-eslint@v1

    - name: Tests
      run: npm test
  
